---
 - hosts: all
   tasks:
   - name: get date and time
     vars:
      msg: |
       Date: {{ ansible_date_time.date }}
       Timezone: {{ ansible_date_time.tz }}
     copy:
      dest: "./date_time"
      content: "{{ msg }}"

   - name: network info
     vars:
      msg: |
       All Interface List: {{ ansible_interfaces }}
       All IP: {{ ansible_all_ipv4_addresses }}
       Gateway: {{ ansible_default_ipv4.gateway }}
       Eth0 MAC: {{ ansible_eth0.macaddress }}
     copy:
      dest: "./network"
      content: "{{ msg }}"

   - name: OS and Kernel info
     vars:
      msg: |
       Distribution: {{ ansible_distribution }}
       Release: {{ ansible_distribution_release }}
       Distribution Version: {{ ansible_distribution_version }}
       Kernel: {{ ansible_kernel }}
       Architecture: {{ ansible_architecture }}
     copy:
       dest: "./os_kernel"
       content: "{{ msg }}"

   - name: get hardware info
     vars:
      msg: |
       CPU: {{ ansible_processor }}
       CPU Core: {{ ansible_processor_cores }}
       RAM: {{ ansible_memtotal_mb }}
       SWAP: {{ ansible_memory_mb.swap.total }}
     copy:
      dest: "./hardware"
      content: "{{ msg }}"
   - name  
   - name: unite files in a node
     ansible.builtin.shell: cat hostname date_time network os_kernel hardware > send_info.txt

   - name: collect files from nodes
     ansible.builtin.fetch:
       src: send_info.txt
       dest: info/info_{{ inventory_hostname }}.txt
       flat: yes
